apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: mm2-europe
  # namespace: europe
  labels:
    eventstreams.ibm.com/cluster: eu-eventstreams
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # access to the topics that MirrorMaker will consume messages from
      - operations:
          - DescribeConfigs
          - Read
        resource:
          name: LH.
          patternType: prefix
          type: topic


      # topics that MirrorMaker will create and produce mirror'ed messages to
      - operations:
          - Create
          - Alter
          - AlterConfigs
          - Write
        resource:
          name: northamerica.LH.
          patternType: prefix
          type: topic
      - operations:
          - Create
          - Alter
          - AlterConfigs
          - Write
        resource:
          name: southamerica.LH.
          patternType: prefix
          type: topic


      # consumer group that will be used by MirrorMaker
      - operations:
          - Read
        resource:
          name: mm2-eu
          type: group


      # access to the topics that MirrorMaker uses to store state
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_eu_offsets
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_eu_configs
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_eu_status
          type: topic
      - operations:
          - Create
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: mm2-offset-syncs.northamerica.internal
          type: topic
      - operations:
          - Create
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: mm2-offset-syncs.southamerica.internal
          type: topic
