---

- name: Create namespace {{ namespace }}
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    validate_certs: false

- name: Define the Entitled Registry pull secret for the {{ namespace }} namespace
  ansible.builtin.set_fact:
    entitled_registry_secret: "{{ [ lookup('template', './templates/docker-pull-secret.yaml') | ansible.builtin.from_yaml ] }}"
  vars:
    docker_secret_password: "{{ ibm_entitlement_key }}"

- name: Create a secret in the {{ namespace }} namespace for the Entitled Registry key
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ibm-entitlement-key
        namespace: "{{ namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ entitled_registry_secret[0] | to_json | string | b64encode }}"
    validate_certs: false


# --------------------------------------------------------------------
#  additional namespace resources in support of metrics collection
# --------------------------------------------------------------------

- name: Define metrics collection rules for {{ namespace }}
  kubernetes.core.k8s:
    validate_certs: false
    state: present
    name: "eventstreams-metrics"
    namespace: "{{ namespace }}"
    template: "{{ playbook_dir }}/../common/create-regions/templates/metrics.yaml"
    wait: false

- name: Prepare pod monitors for {{ namespace }}
  kubernetes.core.k8s:
    validate_certs: false
    state: present
    namespace: "{{ namespace }}"
    template: "{{ playbook_dir }}/../common/create-regions/templates/pod-monitors.yaml"
  vars:
    namespace: "{{ namespace }}"
