---

- name: Create namespaces
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-regions/create-namespace.yaml"
  vars:
    namespace: "{{ namespace_prefix }}{{ item }}"
  loop:
    - north-america
    - south-america
    - europe

- name: Create Event Streams clusters
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-regions/create-cluster.yaml"
  vars:
    namespace: "{{ namespace_prefix }}{{ item.namespace }}"
    es_cluster: "{{ item.es_cluster }}"
  loop:
    - namespace: north-america
      es_cluster: na-eventstreams
    - namespace: south-america
      es_cluster: sa-eventstreams
    - namespace: europe
      es_cluster: eu-eventstreams
