---
- name: Backup / restore - resume applications using the restored cluster
  hosts: localhost
  connection: local
  # vars:
  #   ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"
  #   storage_class: "{{ undef(hint='Provide the storage class to use for Event Streams')}}"
  #   namespace_prefix: "{{ undef(hint='Specify a prefix to use for namespace names')}}"

  tasks:
    - name: Remove the Mirror Maker 2 job used to restore events
      ansible.builtin.include_tasks: "{{ playbook_dir }}/04-resume-applications/remove-restore-mm2.yaml"

    - name: Resume the applications using the restored cluster
      ansible.builtin.include_tasks: "{{ playbook_dir }}/04-resume-applications/resume-everything.yaml"
