apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: eu-eventstreams
  namespace: europe
spec:
  adminApi: {}
  adminUI:
    authentication:
      - type: scram-sha-512
  license:
    accept: true
    license: L-AUKS-FKVXVL
    use: EventAutomationNonProduction
  strimziOverrides:
    # reuse the same certificate authority from the
    #  original cluster, rather than generate new ones
    clusterCa:
      generateCertificateAuthority: false
    clientsCa:
      generateCertificateAuthority: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      authorization:
        type: simple
      config:
        auto.create.topics.enable: false
      listeners:
        - name: internal
          authentication:
            type: scram-sha-512
          port: 9098
          tls: true
          type: internal
      replicas: 3
      storage:
        type: persistent-claim
        size: 10Gi
        class: {{ storage_class }}
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        size: 2Gi
        class: {{ storage_class }}
  version: latest
