apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: datagen-host
  annotations:
    eventstreams.ibm.com/use-connector-resources: 'true'
spec:
  config:
    group.id: datagen-connect-group
    client.id: datagen-connect-client
    config.storage.topic: datagen-configs
    offset.storage.topic: datagen-offsets
    status.storage.topic: datagen-status
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  bootstrapServers: '{{ es_cluster }}-kafka-bootstrap.{{ es_namespace }}.svc:9098'
  resources:
    limits:
      cpu: 1024m
      memory: 1Gi
    requests:
      cpu: 1024m
      memory: 1Gi
  authentication:
    passwordSecret:
      password: password
      secretName: producer-credentials
    type: scram-sha-512
    username: producer-credentials
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          productVersion: 11.6.1
          productID: 2a79e49111f44ec3acd89608e56138f5
          cloudpakName: IBM Cloud Pak for Integration
          productChargedContainers: datagen-host-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Streams for Non Production
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: {{ es_cluster }}-cluster-ca-cert
  replicas: 1
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/{{ producer_namespace }}/mm2-demo-producer:0.0.1
    plugins:
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.4/kafka-connect-loosehangerjeans-source-0.0.4-jar-with-dependencies.jar
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: eventstreams-metrics
        key: connect-metrics-config.yaml
