apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: mm2-europe
  # namespace: europe
  labels:
    eventstreams.ibm.com/cluster: eu-eventstreams
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # consumer groups that will be used by MirrorMaker
      - operations:
          - Read
        resource:
          name: mm2-na
          type: group
      - operations:
          - Read
        resource:
          name: mm2-sa
          type: group
      # access to the topics that MirrorMaker uses to store state
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_na_configs
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_na_status
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_na_offsets
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_sa_configs
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_sa_status
          type: topic
      - operations:
          - Create
          - Describe
          - DescribeConfigs
          - Read
          - Write
        resource:
          name: __mm2_sa_offsets
          type: topic
      # topics that MirrorMaker will create and produce mirror'ed messages to
      - operations:
          - Create
          - Alter
          - AlterConfigs
          - Write
        resource:
          name: northamerica.LH.
          patternType: prefix
          type: topic
      - operations:
          - Create
          - Alter
          - AlterConfigs
          - Write
        resource:
          name: southamerica.LH.
          patternType: prefix
          type: topic
      # support for using transactions
      - operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
