---
- name: Shared aggregate - with mirror maker used to maintain a logical topic distributed across multiple regions
  hosts: localhost
  connection: local
  # vars:
  #   ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"
  #   storage_class: "{{ undef(hint='Provide the storage class to use for Event Streams')}}"
  #   namespace_prefix: "{{ undef(hint='Specify a prefix to use for namespace names')}}"

  tasks:
    - name: Check for required variables
      fail:
        msg: "Required variable {{item}} has not been provided"
      when: vars[item] is undefined
      loop:
        - ibm_entitlement_key
        - storage_class
        - namespace_prefix

    - name: Check for playbook pre-requisites
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/pre-reqs/playbook-prereqs.yaml"

    # In shared Lab environments, this will be done already
    # - name: Install Event Streams
    #   ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/install-eventstreams/setup.yaml"

    - name: Create the North America, South America, and Europe regions
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-regions/setup.yaml"

    - name: Start producers in all regions
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/producer/setup.yaml"
      vars:
        namespace: "{{ namespace_prefix }}{{ item.namespace }}"
        es_cluster: "{{ item.es_cluster }}"
        region: "{{ item.region }}"
        locations: "{{ item.locations }}"
      loop:
        - namespace: north-america
          es_cluster: na-eventstreams
          region: NA
          locations: "Atlanta,Chicago,Dallas,Detroit,Philadelphia"
        - namespace: south-america
          es_cluster: sa-eventstreams
          region: SA
          locations: "SãoPaulo,BuenosAires,Lima,Bogotá,LaPaz"
        - namespace: europe
          es_cluster: eu-eventstreams
          region: EU
          locations: "Antwerp,Rotterdam,Dusseldorf,Brussels,Hamburg"

    - name: Set up Mirror Maker 2 instances
      ansible.builtin.include_tasks: "{{ playbook_dir }}/start-mm2.yaml"

    - name: Start consumers in all regions
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/consumer/setup.yaml"
      vars:
        namespace: "{{ namespace_prefix }}{{ item.namespace }}"
        consumer: "{{ item.consumer }}"
        user_template: "{{ item.user_template }}"
        es_cluster: "{{ item.es_cluster }}"
        es_namespace: "{{ namespace_prefix }}{{ item.es_namespace }}"
        topics: "{{ item.topics }}"
      loop:
        - namespace: north-america
          consumer: consumer-northamerica
          user_template: "{{ playbook_dir }}/templates/consumer-na.yaml"
          es_cluster: na-eventstreams
          es_namespace: north-america
          topics: !unsafe '.*LH\\.ORDERS'
        - namespace: south-america
          consumer: consumer-southamerica
          user_template: "{{ playbook_dir }}/templates/consumer-sa.yaml"
          es_cluster: sa-eventstreams
          es_namespace: south-america
          topics: !unsafe '.*LH\\.ORDERS'
        - namespace: europe
          consumer: consumer-europe
          user_template: "{{ playbook_dir }}/templates/consumer-eu.yaml"
          es_cluster: eu-eventstreams
          es_namespace: europe
          topics: !unsafe '.*LH\\.ORDERS'
