#!/bin/bash

echo "======================================================================="
echo " Login details "
echo "======================================================================="
echo "North America region:"
echo ""
echo "$(oc get eventstreams na-eventstreams -n ${NAMESPACE_PREFIX}north-america -o jsonpath='{.status.adminUiUrl}')"
echo "user:     es-admin"
echo "password: $(oc get secret es-admin -n ${NAMESPACE_PREFIX}north-america -o jsonpath='{.data.password}' | base64 -d)"
echo ""
echo "-----------------------------------------------------------------------"
echo "South America region:"
echo ""
echo "$(oc get eventstreams sa-eventstreams -n ${NAMESPACE_PREFIX}south-america -o jsonpath='{.status.adminUiUrl}')"
echo "user:     es-admin"
echo "password: $(oc get secret es-admin -n ${NAMESPACE_PREFIX}south-america -o jsonpath='{.data.password}' | base64 -d)"
echo ""
echo "-----------------------------------------------------------------------"
echo "Europe region:"
echo ""
echo "$(oc get eventstreams eu-eventstreams -n ${NAMESPACE_PREFIX}europe -o jsonpath='{.status.adminUiUrl}')"
echo "user:     es-admin"
echo "password: $(oc get secret es-admin -n ${NAMESPACE_PREFIX}europe -o jsonpath='{.data.password}' | base64 -d)"
echo ""
echo "======================================================================="
