apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: mm2-northamerica-backup
  # namespace: north-america
  labels:
    eventstreams.ibm.com/cluster: na-eventstreams
spec:
  authentication:
    type: scram-sha-512
    # restore the password from before the loss of the
    #  primary cluster, to allow MM2 to resume without
    #  reconfiguration
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: backup-na-mm2-northamerica-backup
  authorization:
    type: simple
    acls:
      # access to the topics that MirrorMaker will consume messages from
      - operations:
          - DescribeConfigs
          - Read
        resource:
          name: LH.
          patternType: prefix
          type: topic
      # access to the consumer groups that Mirror Maker will sync
      - operations:
          - Describe
        resource:
          type: group
          name: consumer-
          patternType: prefix
      # access to the consumer groups that Mirror Maker will sync
      - operations:
          - Describe
        resource:
          type: cluster
