apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: es-admin
  labels:
    app.kubernetes.io/instance: na-eventstreams
    eventstreams.ibm.com/cluster: na-eventstreams
spec:
  authentication:
    type: scram-sha-512
    # restore the password from before the loss of the
    #  primary cluster, to allow administrators to
    #  use the same credentials they already have
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: backup-na-es-admin
  authorization:
    type: simple
    acls:
      - operations:
          - Alter
          - DescribeConfigs
        resource:
          type: cluster
      - operations:
          - Create
          - Read
          - Write
          - Delete
          - DescribeConfigs
          - Alter
          - AlterConfigs
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operations:
          - Read
          - Delete
        resource:
          name: '*'
          patternType: literal
          type: group
