---

- name: Create namespaces
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-regions/create-namespace.yaml"
  vars:
    namespace: "{{ item }}"
  loop:
    - north-america
    - south-america
    - europe

- name: Create Event Streams clusters
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-regions/create-cluster.yaml"
  vars:
    namespace: "{{ item.namespace }}"
    es_cluster: "{{ item.es_cluster }}"
  loop:
    # active cluster
    - namespace: north-america
      es_cluster: na-eventstreams
    # passive failover cluster
    - namespace: europe
      es_cluster: eu-eventstreams
