apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
# metadata:
  # name: eventstreams
spec:
  adminApi: {}
  adminUI:
    authentication:
      - type: scram-sha-512
  license:
    accept: true
    license: L-AUKS-FKVXVL
    use: EventAutomationNonProduction
  strimziOverrides:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            name: eventstreams-metrics
            key: kafka-metrics-config.yaml
      authorization:
        type: simple
      config:
        auto.create.topics.enable: false
      listeners:
        - name: internal
          authentication:
            type: scram-sha-512
          port: 9098
          tls: true
          type: internal
      replicas: 3
      storage:
        type: persistent-claim
        size: 10Gi
        class: {{ storage_class }}
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        size: 2Gi
        class: {{ storage_class }}
  version: latest