---
- name: Fetch secret {{ secret }} from origin namespace {{ origin }}
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ origin }}"
    name: "{{ secret }}"
  register: origin_secret

- name: Create secret {{ secret }} in destination namespace {{ destination }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ secret }}"
        namespace: "{{ destination }}"
      data: "{{ origin_secret.resources[0].data }}"
